# Generated by Django 5.2.9 on 2025-12-10 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainScreenQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('subtitle', models.CharField(max_length=200)),
                ('section_label', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Main Screen Question',
                'verbose_name_plural': 'Main Screen Question',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=10, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('subtitle', models.CharField(max_length=200)),
                ('checkpoint_label', models.CharField(max_length=200)),
                ('instruction', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('avatar', models.URLField(blank=True)),
                ('affirmed', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_id', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=500)),
                ('subtitle', models.CharField(max_length=500)),
                ('image', models.URLField(blank=True)),
                ('description', models.TextField()),
                ('why_this_matters', models.TextField(blank=True)),
                ('research_evidence', models.TextField(blank=True)),
                ('decision_impact', models.TextField(blank=True)),
                ('what_you_are_fighting_for', models.TextField(blank=True)),
                ('cooperative_learning', models.TextField(blank=True)),
                ('barriers_to_access', models.TextField(blank=True)),
                ('care_team_affirmation', models.TextField(blank=True)),
                ('interdependency_at_work', models.TextField(blank=True)),
                ('reflection_guidance', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='questionnaire.question')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('question', 'choice_id')},
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='questionnaire.question')),
                ('selected_choices', models.ManyToManyField(blank=True, to='questionnaire.choice')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user_id', 'question')},
            },
        ),
    ]
